name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  youtube_player_flutter: ^9.1.3
  youtube_explode_dart: ^3.0.5 # Usamos la original
  path_provider: ^2.1.5
  just_audio: ^0.10.5
  permission_handler: ^12.0.1
  path: ^1.9.1
  audio_service: ^0.18.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Anulación correcta:
# Forzamos a todo el proyecto (incluyendo las dependencias de youtube_player_flutter)
# a usar la versión 3.0.5 de youtube_explode_dart.
dependency_overrides:
  youtube_explode_dart: ^3.0.5

flutter:
  uses-material-design: true
